### ISSUE TITLE
Transform class issue tracker

### ISSUE THREAD

**Issue by Pessimistress** [uber/luma.gl#523] opened 2018-05-24 18:05 UTC
1. If `destinationBuffers` is not provided, `Transform` generates a buffer using the source buffer layout. This does not account for source buffers that are not Buffer objects (e.g. generic attribute).
2. If `elementCount` is changed via `update`, the automatically generated destination buffers are not resized.

@1chandu

**Comment by ibgreen** [comment] 2018-06-27 15:40
Duplicate of #576

**Closed by ibgreen** 2018-06-27 15:40 UTC
