### ISSUE TITLE
Enable tree-shaking

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#757] opened 2018-10-12 22:50 UTC
Leftover work from 6.2 release:

- Tree-Shaking

  Re-enable sideEffects (in package.json) and test bundling / tree shaking in production app - layer-browser (@ibgreen)

**Comment by ibgreen** [comment] 2018-12-19 20:19
Duplicate of #704

**Closed by ibgreen** 2018-12-19 20:19 UTC
