### ISSUE TITLE
Transform: Enhancements

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#475] opened 2018-03-28 15:42 UTC
#### Background 
Based on review discussions from `Transform` related PRs.
#### To Do List 
  - [X] Add label and assign to milestone 
  - [ ] Coding
      - [ ]  Avoid parsing the shader in `Transform` class for version string.
         - [ ] Add a getter to `Shader` class to return version information.
         - [ ] In `Transform` class build `Shader` object for `vs` if not provided, and based on its `version` pick a prebuilt passthrough `fs`.
      - [ ] When `sourceDestinationMap` is provided deduce `varyings` from it.
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by ibgreen** [comment] 2018-06-27 15:38
Duplicate of #576

**Closed** 2018-06-27 15:38 UTC
Labels: enhancement
