### ISSUE TITLE
Support Flat Shading in Geometries, esp. CylinderGeometry

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#994] opened 2019-03-20 15:50 UTC
#### Background 

See https://github.com/uber/deck.gl/pull/2808. 

CylinderPrimitive can be used for Hexagons, Square columns etc but construction of normals always results in smooth shading.

#### To Do List 
- [ ] Decide whether to implement shading options in current primitive(s) or create new primitive(s).
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by tsherif** [comment] 2019-03-20 17:36
Are you thinking of doing this via normals calculated in the shader?

**Comment by ibgreen** [comment] 2019-03-20 17:44
No nothing clever like that, although open to suggestions.

I was just thinking that by providing e.g. a new `Column` primitive, we would duplicate the corners for the various faces instead of sharing them which allows us to have all normals for each face pointing in the same direction, instead of having "shared" normals that are directed radially out from the column center.

```
   \     /          |   |
    -----           -----
  	|   |         - |   | -
  	|   |         - |   | -
    -----           -----
```

**Comment by tsherif** [comment] 2019-03-20 17:53
I'd suggest try calculating them in the fs using standard derivatives:
```js
vec3 normal = normalize(cross(dFdx(fragmentPos), dFdy(fragmentPos)));
```
If that gets the results you need, you save on memory and bandwidth by not having to send the normals at all.

**Comment by ibgreen** [comment] 2019-03-20 18:31
Clever! 

Some issues:
* Our default phong-lighting system is vertex shader based for perf reasons (PBR lighting is fragment shader based). I suspect derivatives are not available in vs?
*  Does depend on a WebGL1 extension, maybe you have information on how well supported it is. I would be particularly worried about IE11 support.
* I suppose that if we still provide normals, we could simply fall back to smooth shading if the extension is not available, which I personally think could be acceptable.

**Comment by tsherif** [comment] 2019-03-20 18:40
Wouldn't be available in the vertex shader as it's a pixel-to-pixel derivative.

The WebGL 1 extension is `OES_standard_derivatives`, which has 100% support: https://webglstats.com/webgl/extension/OES_standard_derivatives

**Comment by tsherif** [comment] 2019-04-11 16:16
Closing this as duplicate of #1046

**Closed by tsherif** 2019-04-11 16:16 UTC
