### ISSUE TITLE
I have many warnings was not found in 'math.gl'

### ISSUE THREAD

**Issue by batazor** [uber/luma.gl#462] opened 2018-03-23 13:20 UTC
#### Actual Result

I get many warnings in the console on webpack 3/4

`package.json`
```
"deck.gl": "^5.1.3",
"luma.gl": "^5.1.3",
"react-map-gl": "^3.2.5",
```

```
WARNING in ../node_modules/luma.gl/dist-es6/index.js
81:0-78 "export 'default' (reexported as 'lighting') was not found in './shadertools/modules/lighting/lighting'
...
WARNING in ../node_modules/luma.gl/dist-es6/index.js
98:0-99:111 "export 'Euler' was not found in 'math.gl'
...
WARNING in ../node_modules/luma.gl/dist-es6/index.js
98:0-99:111 "export 'SphericalCoordinates' was not found in 'math.gl'
 @ ../node_modules/luma.gl/dist-es6/index.js
 @ ../node_modules/deck.gl/dist-es6/effects/experimental/reflection-effect/reflection-effect.js
 @ ../node_modules/deck.gl/dist-es6/index.js
 @ ./components/Widget/MapGL/deckgl-overlay.js
```

#### To Do List 
  - [x] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by 1chandu** [comment] 2018-03-23 16:25
Looks like this is not specific to `math.gl` as you have warning for `shadertools` which is exported from `luma.gl`.

```
WARNING in ../node_modules/luma.gl/dist-es6/index.js
81:0-78 "export 'default' (reexported as 'lighting') was not found in './shadertools/modules/lighting/lighting'
```

Can you provide more details about your application setup? Do you see any other errors? Can you try running examples provided in `deck.gl` repo (`deck.gl/examples`)?

**Comment by ibgreen** [comment] 2018-03-23 16:42
I think these might be real issues
* [luma.gl 5.1-release](https://github.com/uber/luma.gl/blob/ce544c2d95f138145229cf1dda835608c1d41d42/src/index.js#L151)
* [math.gl 1.0-release](https://github.com/uber-web/math.gl/blob/310e7714a102937631c150952b57fbefe001a211/src/index.js#L53)

The export is experimental in math.gl but luma.gl imports it as a main import, so it will be undefined as an export.

They are probably easy, one line fixes.

Suggest we track these down and fix them in 5.1 and 5.2.

**Comment by jianhuang01** [comment] 2018-03-23 18:27
@batazor I can't reproduce the issue, will delete the wrong import anyway and publish a new release. If possible, attach your example here so I can verify the problem.

**Comment by ibgreen** [comment] 2018-03-23 18:44
I believe it is webpack 3 that emits these warnings. We are still using webpack 2. @balthazar

**Comment by balthazar** [comment] 2018-03-23 19:26
It's webpack 4, I fixed these issues a few days ago already in https://github.com/uber/luma.gl/pull/428

**Comment by jianhuang01** [comment] 2018-03-23 20:18
published deck.gl@5.1.4 and luma.gl@5.1.4, should be fixed.

**Closed by jianhuang01** 2018-03-23 20:18 UTC
Labels: bug
