### ISSUE TITLE
New Transform support increases size of minified library

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#734] opened 2018-09-21 00:42 UTC
#### Actual Result
- The test app (that does not import `Transform) grows almost 5K minified and gzipped.

`yarn collect-metrics` before and after this commit:

<img width="556" alt="screen shot 2018-09-20 at 5 36 48 pm" src="https://user-images.githubusercontent.com/7025232/45853797-1aab1400-bcfc-11e8-83ae-579b8117ed19.png">

<img width="546" alt="screen shot 2018-09-20 at 5 36 56 pm" src="https://user-images.githubusercontent.com/7025232/45853802-1e3e9b00-bcfc-11e8-891b-6c10d371b0c9.png">

#### Expected Result
- If `Transform` is not used by app, the new code should (mostly) be tree-shaken out. 
- Need to find why tree-shaking is defeated and refactor.

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by 1chandu** [comment] 2018-09-28 21:17
Re-test the script on master, by including/excluding `Transform` from index files, it shouldn't be included in bundle in the test app when it is not being used.

**Comment by 1chandu** [comment] 2018-10-01 19:22
I am not able reproduce this issue:
(For each test , removed node_modules and dist and rebuild)

with no changes to master : 
<img width="591" alt="master" src="https://user-images.githubusercontent.com/9502731/46310498-67041880-c574-11e8-95ee-5cc56693ef6c.png">

remove importing `Transform` from core `index` file

<img width="588" alt="master_notransforminindex" src="https://user-images.githubusercontent.com/9502731/46310548-8b5ff500-c574-11e8-8a17-ecb5e18a825a.png">

**Comment by 1chandu** [comment] 2018-10-05 17:53
Closing, since this isn't reproducible.

**Closed by 1chandu** 2018-10-05 17:53 UTC
Labels: chore
