### ISSUE TITLE
How to use GLTF model？

### ISSUE THREAD

**Issue by dinglei92** [uber/luma.gl#731] opened 2018-09-17 06:05 UTC
I want to load a GLTF file model, but I don't know how to use it, Is there a relevant example?

**Comment by ibgreen** [comment] 2018-09-17 16:11
@dinglei92 

glTF support is being implemented right now, but not yet ready. We may have an initial loader available in ~2 weeks.

**Comment by ibgreen** [comment] 2018-09-17 16:12
Duplicate of #702

**Comment by dinglei92** [comment] 2018-09-18 00:38
ok, thank you!  I am looking forward.

**Comment by ibgreen** [comment] 2018-12-13 00:00
Tracking in #702

**Closed by ibgreen** 2018-12-13 00:00 UTC
