### ISSUE TITLE
Add ability to support a matrix as instance attribute

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#783] opened 2018-11-18 07:14 UTC
#### Background 
NOTE: Need to be evaluated for real use cases and impact.
Ref: #769 
When a transformation applied is different for each instance, instead of creating an instanced attribute for each factor of transformation (translations, rotation, etc) , build transformation matrix and set it as uniform.

`Pros`: Fewer attribute
`Cons`: When rendering thousands of instances, calculating this matrix for each instance in CPU is less performant compared to doing this on GPU by just setting all factors as attributes.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by tsherif** [comment] 2019-04-11 16:36
Duplicate of #959

**Closed by tsherif** 2019-04-11 16:36 UTC
